name: bahya_mobile
description: Coffee shop local network ERP (Hub/Clients) - Qahwat Al-Balla
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State & utils
  provider: ^6.1.2
  uuid: ^4.4.2

  # Local DB (later we will replace with drift; now keep it light)
  shared_preferences: ^2.2.3

  # QR show/scan + barcode scan
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1

  # Network (Hub/Client)
  http: ^1.2.2
  web_socket_channel: ^2.4.5

  # Sounds (arrival orders)
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
